#!/bin/bash

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.constants.sh"
. "${SCRIPT_DIR}/inc.functions.sh"


for file in ${J2OBJC_FILES}; do
  if [ ! -f "${file}" ]; then
    approve "Downloading ${file}"
    curl -OL https://github.com/google/j2objc/releases/download/${J2OBJC_VERSION}/${file}
    unzip -o -q "${file}"
  fi
done

SOURCE_DIR=java
if [ ! -d "${OUTPUT_DIR}" ]; then 
  approve "Transpiling BouncyCastle to '${OUTPUT_DIR}'"
  mkdir -p "${OUTPUT_DIR}"
  safe "${J2OBJC_PATH}/j2objc" \
      -d "${OUTPUT_DIR}" \
      -sourcepath "${SOURCE_DIR}" \
      --prefixes "scripts/prefixes.properties" \
      --nullability \
      --swift-friendly \
      -use-arc \
      -Xlint:none \
      $(find "${SOURCE_DIR}" -name '*.java')
fi

UMBREALLA_HEADER=BouncyCastle-ObjC
if [ ! -d "${HEADER_DIR}" ]; then
  approve "Generating umbrella header to '${HEADER_DIR}'"
  mkdir -p "${HEADER_DIR}"
  cp ./scripts/${UMBREALLA_HEADER}_template.h "${HEADER_DIR}/${UMBREALLA_HEADER}.h"
  headers="$(cd ${OUTPUT_DIR}; find . -type f -name "*.h" | sed 's|^./||')" 
  for header in ${headers}; do
      echo "#include <${header}>" >> "${HEADER_DIR}/${UMBREALLA_HEADER}.h"
  done

  approve "Copy JRE.xcframework headers to '${HEADER_DIR}'"
  cp -r ${J2OBJC_PATH}/include/* "${OUTPUT_DIR}"
fi
